### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by maertSi** [maertSi/E-Smog-Meter#1]
### todo

Priorität hoch
- [ ] Einstellungsmöglichkeit der Grenzwerte implementieren
- [ ] Auswahl eines Landes, dementsprechend werden Grenzwerte auf den angezeigten Wert angewendet
- [ ] Farbliche Hervorhebung des angezeigten Wertes (zunächst nur in "Betrag"-Seite), gelb + rot
- [ ] Hinzufügen des Navigation-Drawer Titelbildes	

Priorität niedrig
- [ ] - Erstellen der graphischen Ansicht
