### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by maertSi** [maertSi/E-Smog-Meter#2]
### todo

- [ ] Anpassen der Seitenränder, vereinheitlichen auf allen Seiten
- [ ] Text für technischen Hintergrund ergänzen
- [ ] Text für das Tutorial ergänzen
